openapi: 3.0.2
info:
  title: Auth microservice
  version: 1.0.0
  description: OpenAPI specification for Auth microservice
  contact:
    name: AimCup
    email: aimcupdev@gmail.com

paths:
  /me:
    $ref: './paths/user/user.yaml'
  /{osuId}:
    $ref: './paths/user/user-by-osu-id.yaml'
