version: '3.8'

services:
  auth-microservice:
    build:
      context: ../..
      dockerfile: docker/stg/stg-build-deploy.Dockerfile
    ports:
      - "8502:8502"
    environment:
      - EXAMPLE_DB_STG_PASSWORD=${POSTGRES_PASSWORD}


networks:
  default:
    external: true
    name: aimcup-network