version: '3.8'

services:
  user-microservice:
    build:
      context: ../..
      dockerfile: docker/stg/stg-build-deploy.Dockerfile
    ports:
      - "8502:8502"
    environment:
      - DB_STG_ADDRESS=${DB_STG_ADDRESS}
      - DB_STG_USER=${DB_STG_USER}
      - DB_STG_PASSWORD=${DB_STG_PASSWORD}
      - EUREKA_STG=${EUREKA_STG}
      - STG_KEYCLOAK_NAME_ISSUER=${STG_KEYCLOAK_NAME_ISSUER}
      - STG_KEYCLOAK_CLIENT_NAME=${STG_KEYCLOAK_CLIENT_NAME}
      - STG_KEYCLOAK_CLIENT_ID=${STG_KEYCLOAK_CLIENT_ID}
      - STG_KEYCLOAK_CLIENT_SECRET=${STG_KEYCLOAK_CLIENT_SECRET}
      - STG_KEYCLOAK_JWK_SET_URI=${STG_KEYCLOAK_JWK_SET_URI}
      - STG_KEYCLOAK_URI = ${STG_KEYCLOAK_URI}
      - STG_KEYCLOAK_REALM_NAME = ${STG_KEYCLOAK_REALM_NAME}
      - STG_MANAGEMENT_KEYCLOAK_CLIENT_ID = ${STG_MANAGEMENT_KEYCLOAK_CLIENT_ID}
      - STG_MANAGEMENT_KEYCLOAK_CLIENT_SECRET = ${STG_MANAGEMENT_KEYCLOAK_CLIENT_SECRET}
      - STG_OSU_API_CLIENT_SECRET = ${STG_OSU_API_CLIENT_SECRET}
      - STG_OSU_API_CLIENT_ID = ${STG_OSU_API_CLIENT_ID}

networks:
  default:
    external: true
    name: aimcup-network