eureka:
  client:
    enabled: false
server:
  servlet:
    context-path: /user
  port: 8080
spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: testUser
    password: testPassword
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      idle-timeout: 5000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
  security:
    oauth2:
      client:
        provider:
          aimcup:
            issuer-uri: https://keycloak-stg.aimcup.xyz/realms/aimcup-realm
        registration:
          aimcup:
            provider: aimcup
            client-name: aimcup
            client-id: aimcup
            client-secret: MUSDaD5wr0p06E8rwlVXkteKagnr29lU
            scope: profile,openid,offline_access
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
  main:
    allow-bean-definition-overriding: true

aimcup:
  keycloak:
    serverUrl: https://keycloak-stg.aimcup.xyz
    realm: aimcup-realm
    clientId: ac-management
    clientSecret: msZLKuDHgERVggrmZA33xcm2yoqkcYqI

logging:
  level:
    org:
      springframework:
        security: DEBUG