eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.1:8762/eureka
server:
  servlet:
    context-path: /user
  port: 8502
  forward-headers-strategy: native
spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:postgresql://172.18.0.1:5702/user
    username: user
    password: ${USER_DB_STG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      idle-timeout: 5000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak-stg.aimcup.xyz/realms/aimcup-realm/protocol/openid-connect/certs
      client:
        provider:
          aimcup:
            issuer-uri: https://keycloak-stg.aimcup.xyz/realms/aimcup-realm
        registration:
          aimcup:
            provider: aimcup
            client-name: aimcup
            client-id: aimcup
            client-secret: MUSDaD5wr0p06E8rwlVXkteKagnr29lU
            scope: profile,openid,offline_access
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
  main:
    allow-bean-definition-overriding: true

aimcup:
  keycloak:
    serverUrl: https://keycloak-stg.aimcup.xyz
    realm: aimcup-realm
    clientId: ac-management
    clientSecret: msZLKuDHgERVggrmZA33xcm2yoqkcYqI

osu:
  api:
    clientId: 9552
    clientSecret: md6Y4UwjAwTJ3VQAbfwUnzxLlZ6JMRY3ivGJaRkt