eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.1:8761/eureka
server:
  servlet:
    context-path: /user
  port: 8501
spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:postgresql://172.18.0.1:5701/auth
    username: user
    password: ${USER_DB_PRD_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      idle-timeout: 5000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false