version: '3.8'

services:
  auth-microservice:
    build:
      context: ../..
      dockerfile: docker/prd/prd-build-deploy.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - EXAMPLE_DB_PRD_PASSWORD=${POSTGRES_PASSWORD}

networks:
  default:
    external: true
    name: aimcup-network