version: '3.8'

services:
  db-auth-microservice:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5701:5432"

networks:
  default:
    external: true
    name: aimcup-network