version: '3.8'

services:
  user-microservice:
    build:
      context: ../..
      dockerfile: docker/prd/prd-build-deploy.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - DB_PRD_ADDRESS=${DB_PRD_ADDRESS}
      - DB_PRD_USER=${DB_PRD_USER}
      - DB_PRD_PASSWORD=${DB_PRD_PASSWORD}
      - EUREKA_PRD=${EUREKA_PRD}
      - PRD_KEYCLOAK_ISSUER_ID=${PRD_KEYCLOAK_ISSUER_ID}
      - PRD_KEYCLOAK_CLIENT_NAME=${PRD_KEYCLOAK_CLIENT_NAME}
      - PRD_KEYCLOAK_CLIENT_ID=${PRD_KEYCLOAK_CLIENT_ID}
      - PRD_KEYCLOAK_CLIENT_SECRET=${PRD_KEYCLOAK_CLIENT_SECRET}
      - PRD_KEYCLOAK_JWK_SET_URI=${PRD_KEYCLOAK_JWK_SET_URI}
      - PRD_KEYCLOAK_URI = ${PRD_KEYCLOAK_URI}
      - PRD_KEYCLOAK_REALM_NAME = ${PRD_KEYCLOAK_REALM_NAME}
      - PRD_MANAGEMENT_KEYCLOAK_CLIENT_ID = ${PRD_MANAGEMENT_KEYCLOAK_CLIENT_ID}
      - PRD_MANAGEMENT_KEYCLOAK_CLIENT_SECRET = ${PRD_MANAGEMENT_KEYCLOAK_CLIENT_SECRET}
      - PRD_OSU_API_CLIENT_SECRET = ${PRD_OSU_API_CLIENT_SECRET}
      - PRD_OSU_API_CLIENT_ID = ${PRD_OSU_API_CLIENT_ID}

networks:
  default:
    external: true
    name: aimcup-network