name: Deploy to Staging

on:
  pull_request:
    types:
      - closed
    branches:
      - stage

jobs:
  build:
    runs-on:
      group: Default
    steps:
      - name: Setup Maven settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ secrets.SETTINGS_XML_USERNAME }}",
                "password": "${{ secrets.SETTINGS_XML_TOKEN }}"
            }]
      - uses: actions/checkout@v3
      - name: Run microservice db (if needed)
        run: |
          docker-compose -f docker/stg/stg-run-database-job.yml up -d --build
        env:
          POSTGRES_PASSWORD: ${{ secrets.USER_DB_STG_PASSWORD }}
      - name: Build and deploy the Docker image
        run: |
          docker-compose -f docker/stg/stg-build-deploy-job.yml up -d --build
        env:
          POSTGRES_PASSWORD: ${{ secrets.USER_DB_STG_PASSWORD }}